
package com.company.project.module.eam.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "GetDataInterfaceService", targetNamespace = "http://www.joven.com.cn/ws/GetDataInterfaceService", wsdlLocation = "http://192.168.1.248:26086/otm/ws/GetDataInterfaceService?wsdl")
public class GetDataInterfaceService_Service
    extends Service
{

    private final static URL GETDATAINTERFACESERVICE_WSDL_LOCATION;
    private final static WebServiceException GETDATAINTERFACESERVICE_EXCEPTION;
    private final static QName GETDATAINTERFACESERVICE_QNAME = new QName("http://www.joven.com.cn/ws/GetDataInterfaceService", "GetDataInterfaceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.1.248:26086/otm/ws/GetDataInterfaceService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        GETDATAINTERFACESERVICE_WSDL_LOCATION = url;
        GETDATAINTERFACESERVICE_EXCEPTION = e;
    }

    public GetDataInterfaceService_Service() {
        super(__getWsdlLocation(), GETDATAINTERFACESERVICE_QNAME);
    }

    public GetDataInterfaceService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), GETDATAINTERFACESERVICE_QNAME, features);
    }

    public GetDataInterfaceService_Service(URL wsdlLocation) {
        super(wsdlLocation, GETDATAINTERFACESERVICE_QNAME);
    }

    public GetDataInterfaceService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GETDATAINTERFACESERVICE_QNAME, features);
    }

    public GetDataInterfaceService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GetDataInterfaceService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns GetDataInterfaceService
     */
    @WebEndpoint(name = "GetDataInterfaceServicePort")
    public GetDataInterfaceService getGetDataInterfaceServicePort() {
        return super.getPort(new QName("http://www.joven.com.cn/ws/GetDataInterfaceService", "GetDataInterfaceServicePort"), GetDataInterfaceService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GetDataInterfaceService
     */
    @WebEndpoint(name = "GetDataInterfaceServicePort")
    public GetDataInterfaceService getGetDataInterfaceServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.joven.com.cn/ws/GetDataInterfaceService", "GetDataInterfaceServicePort"), GetDataInterfaceService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GETDATAINTERFACESERVICE_EXCEPTION!= null) {
            throw GETDATAINTERFACESERVICE_EXCEPTION;
        }
        return GETDATAINTERFACESERVICE_WSDL_LOCATION;
    }

}
